// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ImageConvert(arg1:main.ImageConvertOptions):Promise<void>;

export function MediaConvert(arg1:main.MediaConvertOptions):Promise<void>;
