// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MediaConvert(arg1) {
  return window['go']['main']['App']['MediaConvert'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
