// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function MediaConvert(arg1:main.MediaConvertOptions):Promise<Array<number>>;

export function RemoveFile(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
